name: clauselens
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - pip:
      - streamlit
      - fpdf2
      - sentence-transformers
      - torch==2.2.2
      - torchvision
      - torchaudio

